languageCode = "ja"
title = "とにかくやってみた。"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://flaflasun.github.io/tonikaku-yattemita"
canonifyurls = true
author = "flaflasun"

[indexes]
    category = "categories"
    tag = "tags"
[Params]
    AuthorName = "flaflasun"
    github = "flaflasun/tonikaku-yattemita"
    twitter = "flaflasun"
